/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WidgetMode } from "./types";
export { WidgetMode } from "./types";
export namespace Components {
    interface S2pAnnotationLayer {
    }
    interface S2pAnnotationMarkers {
    }
    interface S2pAnnotationPopup {
    }
    interface S2pLayoutPanel {
        /**
          * When true, dropped components go to wireframePlacements (canvas mode)
          * @default false
         */
        "canvasMode": boolean;
    }
    /**
     * Draggable toolbar component
     * Features:
     *   - Drag via PointerEvents (no external deps)
     *   - Mode buttons (annotation/layout/wireframe)
     *   - Copy and Clear buttons
     *   - Settings button
     *   - Annotation count badge
     *   - Keyboard shortcut: Cmd+Shift+F to toggle
     */
    interface S2pToolbar {
        /**
          * @default 0
         */
        "annotationCount": number;
        /**
          * @default "idle"
         */
        "mode": WidgetMode;
        /**
          * @default 0
         */
        "placementCount": number;
    }
    interface S2pWidget {
        /**
          * @default false
         */
        "dontShowInProd": boolean;
    }
    interface S2pWireframeCanvas {
    }
    interface S2pWireframeItem {
        /**
          * When true, reads/writes wireframePlacements instead of placements
          * @default false
         */
        "canvas": boolean;
        "placementId": string;
    }
}
export interface S2pToolbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLS2pToolbarElement;
}
declare global {
    interface HTMLS2pAnnotationLayerElement extends Components.S2pAnnotationLayer, HTMLStencilElement {
    }
    var HTMLS2pAnnotationLayerElement: {
        prototype: HTMLS2pAnnotationLayerElement;
        new (): HTMLS2pAnnotationLayerElement;
    };
    interface HTMLS2pAnnotationMarkersElement extends Components.S2pAnnotationMarkers, HTMLStencilElement {
    }
    var HTMLS2pAnnotationMarkersElement: {
        prototype: HTMLS2pAnnotationMarkersElement;
        new (): HTMLS2pAnnotationMarkersElement;
    };
    interface HTMLS2pAnnotationPopupElement extends Components.S2pAnnotationPopup, HTMLStencilElement {
    }
    var HTMLS2pAnnotationPopupElement: {
        prototype: HTMLS2pAnnotationPopupElement;
        new (): HTMLS2pAnnotationPopupElement;
    };
    interface HTMLS2pLayoutPanelElement extends Components.S2pLayoutPanel, HTMLStencilElement {
    }
    var HTMLS2pLayoutPanelElement: {
        prototype: HTMLS2pLayoutPanelElement;
        new (): HTMLS2pLayoutPanelElement;
    };
    interface HTMLS2pToolbarElementEventMap {
        "modeChange": WidgetMode;
    }
    /**
     * Draggable toolbar component
     * Features:
     *   - Drag via PointerEvents (no external deps)
     *   - Mode buttons (annotation/layout/wireframe)
     *   - Copy and Clear buttons
     *   - Settings button
     *   - Annotation count badge
     *   - Keyboard shortcut: Cmd+Shift+F to toggle
     */
    interface HTMLS2pToolbarElement extends Components.S2pToolbar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLS2pToolbarElementEventMap>(type: K, listener: (this: HTMLS2pToolbarElement, ev: S2pToolbarCustomEvent<HTMLS2pToolbarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLS2pToolbarElementEventMap>(type: K, listener: (this: HTMLS2pToolbarElement, ev: S2pToolbarCustomEvent<HTMLS2pToolbarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLS2pToolbarElement: {
        prototype: HTMLS2pToolbarElement;
        new (): HTMLS2pToolbarElement;
    };
    interface HTMLS2pWidgetElement extends Components.S2pWidget, HTMLStencilElement {
    }
    var HTMLS2pWidgetElement: {
        prototype: HTMLS2pWidgetElement;
        new (): HTMLS2pWidgetElement;
    };
    interface HTMLS2pWireframeCanvasElement extends Components.S2pWireframeCanvas, HTMLStencilElement {
    }
    var HTMLS2pWireframeCanvasElement: {
        prototype: HTMLS2pWireframeCanvasElement;
        new (): HTMLS2pWireframeCanvasElement;
    };
    interface HTMLS2pWireframeItemElement extends Components.S2pWireframeItem, HTMLStencilElement {
    }
    var HTMLS2pWireframeItemElement: {
        prototype: HTMLS2pWireframeItemElement;
        new (): HTMLS2pWireframeItemElement;
    };
    interface HTMLElementTagNameMap {
        "s2p-annotation-layer": HTMLS2pAnnotationLayerElement;
        "s2p-annotation-markers": HTMLS2pAnnotationMarkersElement;
        "s2p-annotation-popup": HTMLS2pAnnotationPopupElement;
        "s2p-layout-panel": HTMLS2pLayoutPanelElement;
        "s2p-toolbar": HTMLS2pToolbarElement;
        "s2p-widget": HTMLS2pWidgetElement;
        "s2p-wireframe-canvas": HTMLS2pWireframeCanvasElement;
        "s2p-wireframe-item": HTMLS2pWireframeItemElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface S2pAnnotationLayer {
    }
    interface S2pAnnotationMarkers {
    }
    interface S2pAnnotationPopup {
    }
    interface S2pLayoutPanel {
        /**
          * When true, dropped components go to wireframePlacements (canvas mode)
          * @default false
         */
        "canvasMode"?: boolean;
    }
    /**
     * Draggable toolbar component
     * Features:
     *   - Drag via PointerEvents (no external deps)
     *   - Mode buttons (annotation/layout/wireframe)
     *   - Copy and Clear buttons
     *   - Settings button
     *   - Annotation count badge
     *   - Keyboard shortcut: Cmd+Shift+F to toggle
     */
    interface S2pToolbar {
        /**
          * @default 0
         */
        "annotationCount"?: number;
        /**
          * @default "idle"
         */
        "mode"?: WidgetMode;
        "onModeChange"?: (event: S2pToolbarCustomEvent<WidgetMode>) => void;
        /**
          * @default 0
         */
        "placementCount"?: number;
    }
    interface S2pWidget {
        /**
          * @default false
         */
        "dontShowInProd"?: boolean;
    }
    interface S2pWireframeCanvas {
    }
    interface S2pWireframeItem {
        /**
          * When true, reads/writes wireframePlacements instead of placements
          * @default false
         */
        "canvas"?: boolean;
        "placementId": string;
    }

    interface S2pLayoutPanelAttributes {
        "canvasMode": boolean;
    }
    interface S2pToolbarAttributes {
        "mode": WidgetMode;
        "annotationCount": number;
        "placementCount": number;
    }
    interface S2pWidgetAttributes {
        "dontShowInProd": boolean;
    }
    interface S2pWireframeItemAttributes {
        "placementId": string;
        "canvas": boolean;
    }

    interface IntrinsicElements {
        "s2p-annotation-layer": S2pAnnotationLayer;
        "s2p-annotation-markers": S2pAnnotationMarkers;
        "s2p-annotation-popup": S2pAnnotationPopup;
        "s2p-layout-panel": Omit<S2pLayoutPanel, keyof S2pLayoutPanelAttributes> & { [K in keyof S2pLayoutPanel & keyof S2pLayoutPanelAttributes]?: S2pLayoutPanel[K] } & { [K in keyof S2pLayoutPanel & keyof S2pLayoutPanelAttributes as `attr:${K}`]?: S2pLayoutPanelAttributes[K] } & { [K in keyof S2pLayoutPanel & keyof S2pLayoutPanelAttributes as `prop:${K}`]?: S2pLayoutPanel[K] };
        "s2p-toolbar": Omit<S2pToolbar, keyof S2pToolbarAttributes> & { [K in keyof S2pToolbar & keyof S2pToolbarAttributes]?: S2pToolbar[K] } & { [K in keyof S2pToolbar & keyof S2pToolbarAttributes as `attr:${K}`]?: S2pToolbarAttributes[K] } & { [K in keyof S2pToolbar & keyof S2pToolbarAttributes as `prop:${K}`]?: S2pToolbar[K] };
        "s2p-widget": Omit<S2pWidget, keyof S2pWidgetAttributes> & { [K in keyof S2pWidget & keyof S2pWidgetAttributes]?: S2pWidget[K] } & { [K in keyof S2pWidget & keyof S2pWidgetAttributes as `attr:${K}`]?: S2pWidgetAttributes[K] } & { [K in keyof S2pWidget & keyof S2pWidgetAttributes as `prop:${K}`]?: S2pWidget[K] };
        "s2p-wireframe-canvas": S2pWireframeCanvas;
        "s2p-wireframe-item": Omit<S2pWireframeItem, keyof S2pWireframeItemAttributes> & { [K in keyof S2pWireframeItem & keyof S2pWireframeItemAttributes]?: S2pWireframeItem[K] } & { [K in keyof S2pWireframeItem & keyof S2pWireframeItemAttributes as `attr:${K}`]?: S2pWireframeItemAttributes[K] } & { [K in keyof S2pWireframeItem & keyof S2pWireframeItemAttributes as `prop:${K}`]?: S2pWireframeItem[K] } & OneOf<"placementId", S2pWireframeItem["placementId"], S2pWireframeItemAttributes["placementId"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "s2p-annotation-layer": LocalJSX.IntrinsicElements["s2p-annotation-layer"] & JSXBase.HTMLAttributes<HTMLS2pAnnotationLayerElement>;
            "s2p-annotation-markers": LocalJSX.IntrinsicElements["s2p-annotation-markers"] & JSXBase.HTMLAttributes<HTMLS2pAnnotationMarkersElement>;
            "s2p-annotation-popup": LocalJSX.IntrinsicElements["s2p-annotation-popup"] & JSXBase.HTMLAttributes<HTMLS2pAnnotationPopupElement>;
            "s2p-layout-panel": LocalJSX.IntrinsicElements["s2p-layout-panel"] & JSXBase.HTMLAttributes<HTMLS2pLayoutPanelElement>;
            /**
             * Draggable toolbar component
             * Features:
             *   - Drag via PointerEvents (no external deps)
             *   - Mode buttons (annotation/layout/wireframe)
             *   - Copy and Clear buttons
             *   - Settings button
             *   - Annotation count badge
             *   - Keyboard shortcut: Cmd+Shift+F to toggle
             */
            "s2p-toolbar": LocalJSX.IntrinsicElements["s2p-toolbar"] & JSXBase.HTMLAttributes<HTMLS2pToolbarElement>;
            "s2p-widget": LocalJSX.IntrinsicElements["s2p-widget"] & JSXBase.HTMLAttributes<HTMLS2pWidgetElement>;
            "s2p-wireframe-canvas": LocalJSX.IntrinsicElements["s2p-wireframe-canvas"] & JSXBase.HTMLAttributes<HTMLS2pWireframeCanvasElement>;
            "s2p-wireframe-item": LocalJSX.IntrinsicElements["s2p-wireframe-item"] & JSXBase.HTMLAttributes<HTMLS2pWireframeItemElement>;
        }
    }
}
